Feature:

  Background:
    Given I am on the IPhonePage
    And I click "Write a review"
    And Review tab is opened

  Scenario Outline:
    When I input "<valid name>" in Your Name field
    And I enter "<valid text>" in Your Review field
    And I select rating
    And I click Continue
    Then Success message is shown
    Examples:
      | valid name                | valid text                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
      | Bob                       | gdfsjfkheruicfberuibuecrg                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
      | gdfsjfkheruicfberuibuecrg | gdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrg |
      | John                      | gdfsjfkheruicfberuibuecrg                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
      | Bob                       | gdfsjfkheruicfberuibuecrgd                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
      | Bob                       | gdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrggdfsjfkheruicfberuibuecrg |


  Scenario Outline:
    When I input "<valid name>" in Your Name field
    And I input "<invalid text>" in Your Review field
    And I select rating
    And I click "Continue"
    Then Error message "Warning: Review Text must be between 25 and 1000 characters!" is shown
    Examples:
      | valid name | invalid text                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
      | Bob        | gdfsjfkheruicfberuibuecrfrfbafyfexrrcxtyrxfytrfrgdfsjfkheruicfberuibuecrfrfbafyfexrrcxtyrxfytrfrgdfsjfkheruicfberuibuecrfrfbafyfexrrcxtyrxfytrfrgdfsjfkheruicfberuibuecrfrfbafyfexrrcxtyrxfytrfrgdfsjfkheruicfberuibuecrfrfbafyfexrrcxtyrxfytrfrgdfsjfkheruicfberuibuecrfrfbafyfexrrcxtyrxfytrfrgdfsjfkheruicfberuibuecrfrfbafyfexrrcxtyrxfytrfrgdfsjfkheruicfberuibuecrfrfbafyfexrrcxtyrxfytrfrgdfsjfkheruicfberuibuecrfrfbafyfexrrcxtyrxfytrfrgdfsjfkheruicfberuibuecrfrfbafyfexrrcxtyrxfytrfrgdfsjfkheruicfberuibuecrfrfbafyfexrrcxtyrxfytrfrgdfsjfkheruicfberuibuecrfrfbafyfexrrcxtyrxfytrfrgdfsjfkheruicfberuibuecrfrfbafyfexrrcxtyrxfytrfrgdfsjfkheruicfberuibuecrfrfbafyfexrrcxtyrxfytrfrgdfsjfkheruicfberuibuecrfrfbafyfexrrcxtyrxfytrfrgdfsjfkheruicfberuibuecrfrfbafyfexrrcxtyrxfytrfrgdfsjfkheruicfberuibuecrfrfbafyfexrrcxtyrxfytrfrgdfsjfkheruicfberuibuecrfrfbafyfexrrcxtyrxfytrfrgdfsjfkheruicfberuibuecrfrfbafyfexrrcxtyrxfytrfrgdfsjfkheruicfberuibuecrfrfbafyfexrrcxtyrxfytrfrgdfsjfkheruicfberuibuecrfrfbafyfexrrcxtyr |
      | Bob        | gdfsjfkheruicfberuibuecr                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |

  Scenario:
    When I input "<valid name>" in Your Name field
    And I enter "<valid text>" in Your Review field
    And I do not select rating
    And I click "Continue"
    Then Error "Warning: Please select a review rating!" is shown








